Repository openedx/event-routing-backends, pull requests merged in 2021-07, with the labels that each got.

#96 [ERTE-36] feat: Added transformer version in XAPI transformed events
  event_routing_backends/processors/xapi/constants.py
  event_routing_backends/processors/xapi/transformer.py
Labels: engineering review, open-source-contribution

#105 [ERTE-60] feat: added UUID in xapi statements
  event_routing_backends/processors/xapi/tests/fixtures/expected/complete_video(proposed).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.completed.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.activated.enterprise.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.activated.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.activated.required.only.data.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.deactivated.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.grades.problem.submitted.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.problem.completed(proposed).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.problem.hint.demandhint_displayed.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.link_clicked(anonymous_user).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.link_clicked.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.link_clicked.required.only.data.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.outline.selected.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.sequence.next_selected.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.sequence.previous_selected.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.sequence.tab_selected.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/load_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/pause_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/play_video.empty.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/play_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(browser).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(browser).required.only.data.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server,string_anwers).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(server,unsupported_responsetype).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/seek_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/showanswer.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/stop_video.json
  event_routing_backends/processors/xapi/tests/test_transformers.py
  event_routing_backends/processors/xapi/transformer.py
Labels: needs triage, open-source-contribution

#101 [ERTE-38] feat: Updated the method _match_event_for_host to incorporate list search and regex match
  event_routing_backends/models.py
  event_routing_backends/tests/test_mixin.py
  event_routing_backends/tests/test_models.py
Labels: changes requested, open-source-contribution

#92 [ERTE-32] docs: Created an ADR for access control of events
  docs/decisions/0007-access-control-of-events.rst
  docs/event-mapping/list_of_supported_edx_events.rst
Labels: engineering review, open-source-contribution
