Repository openedx/event-routing-backends, pull requests merged in 2021-06, with the labels that each got.

#78 get username from data dict if not available in context dict of event
  event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.enrollment.activated.enterprise.json
  event_routing_backends/processors/caliper/transformer.py
  event_routing_backends/processors/mixins/base_transformer.py
  event_routing_backends/processors/tests/fixtures/current/edx.course.enrollment.activated.enterprise.json
  event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
  event_routing_backends/processors/xapi/event_transformers/navigation_events.py
  event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
  event_routing_backends/processors/xapi/event_transformers/video_events.py
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.activated.enterprise.json
  event_routing_backends/processors/xapi/transformer.py
Labels: awaiting prioritization, open-source-contribution

#84 Refactor: Added abstraction layer for common data accessor from event and stripping none values
  event_routing_backends/helpers.py
  event_routing_backends/processors/caliper/event_transformers/enrollment_events.py
  event_routing_backends/processors/caliper/event_transformers/navigation_events.py
  event_routing_backends/processors/caliper/event_transformers/problem_interaction_events.py
  event_routing_backends/processors/caliper/event_transformers/video_events.py
  event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.enrollment.activated.required.only.data.json
  event_routing_backends/processors/caliper/tests/fixtures/expected/edx.ui.lms.link_clicked.required.only.data.json
  event_routing_backends/processors/caliper/tests/fixtures/expected/play_video.required.only.data.json
  event_routing_backends/processors/caliper/tests/fixtures/expected/problem_check(browser).required.only.data.json
  event_routing_backends/processors/caliper/tests/test_transformers.py
  event_routing_backends/processors/caliper/transformer.py
  event_routing_backends/processors/mixins/base_transformer.py
  event_routing_backends/processors/tests/fixtures/current/edx.course.enrollment.activated.required.only.data.json
  event_routing_backends/processors/tests/fixtures/current/edx.ui.lms.link_clicked.required.only.data.json
  event_routing_backends/processors/tests/fixtures/current/play_video.required.only.data.json
  event_routing_backends/processors/tests/fixtures/current/problem_check(browser).required.only.data.json
  event_routing_backends/processors/tests/transformers_test_mixin.py
  event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
  event_routing_backends/processors/xapi/event_transformers/navigation_events.py
  event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
  event_routing_backends/processors/xapi/event_transformers/video_events.py
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.enrollment.activated.required.only.data.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.ui.lms.link_clicked.required.only.data.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/play_video.empty.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/problem_check(browser).required.only.data.json
  event_routing_backends/processors/xapi/transformer.py
  event_routing_backends/tests/test_helpers.py
Labels: open-source-contribution, waiting on author

#81 ADR for an accessor method to reduce chances of PII leakage
  docs/decisions/0005-PII-leakage-prevention.rst
Labels: needs triage, open-source-contribution

#83 An ADR for versioning of xAPI and Caliper transformers
  docs/decisions/0006-versioning-of-event-transformers.rst
Labels: needs triage, open-source-contribution

#86 docs: updated docstring of get_data method in base_transfromer.py
  event_routing_backends/processors/mixins/base_transformer.py
Labels: cc-reviewer, engineering review, open-source-contribution

#88 feat: Added course completion event transformer
  event_routing_backends/processors/caliper/event_transformers/enrollment_events.py
  event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.completed.json
  event_routing_backends/processors/tests/fixtures/current/edx.course.completed.json
  event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
  event_routing_backends/processors/xapi/event_transformers/navigation_events.py
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.completed.json
Labels: engineering review, open-source-contribution

#90 Refactor: Find nested keys from common accessor method get data
  event_routing_backends/processors/mixins/base_transformer.py
  event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
Labels: needs triage, open-source-contribution

#91 [ERTE-15-1] docs: added link of accessor method
  docs/decisions/0005-PII-leakage-prevention.rst
Labels: needs triage, open-source-contribution

#94 [ERTE-20-1] docs: changed status to accepted, changed version key name to eventVe…
  docs/decisions/0006-versioning-of-event-transformers.rst
Labels: needs triage, open-source-contribution
