Repository openedx/event-routing-backends, pull requests merged in 2021-09, with the labels that each got.

#122 [ERTE-81] feat: rename edx.course.completed event to edx.course.grade.passed.first_time
  event_routing_backends/processors/caliper/event_transformers/enrollment_events.py
  event_routing_backends/processors/caliper/tests/fixtures/expected/edx.course.grade.passed.first_time.json
  event_routing_backends/processors/tests/fixtures/current/edx.course.grade.passed.first_time.json
  event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
  event_routing_backends/processors/xapi/tests/fixtures/expected/edx.course.grade.passed.first_time.json
Labels: needs triage, open-source-contribution

#124 [ERTE-82] feat: Setup list of business critical event and persist those
  event_routing_backends/backends/events_router.py
  event_routing_backends/backends/tests/test_events_router.py
  event_routing_backends/helpers.py
  event_routing_backends/tasks.py
Labels: needs triage, open-source-contribution

#118 [ERTE-67] Refactor: Integration and testing with mock LRS
  event_routing_backends/backends/events_router.py
  event_routing_backends/backends/tests/test_events_router.py
  event_routing_backends/utils/xapi_lrs_client.py
Labels: needs triage, open-source-contribution

#112 [ERTE-61] Refactor: Add details in logs where EventEmissionExit is raised to distinguish between exceptions.
  event_routing_backends/backends/events_router.py
  event_routing_backends/backends/tests/test_events_router.py
  event_routing_backends/processors/caliper/tests/test_caliper.py
  event_routing_backends/processors/caliper/transformer_processor.py
  event_routing_backends/processors/mixins/base_transformer_processor.py
  event_routing_backends/processors/transformer_utils/exceptions.py
  event_routing_backends/processors/transformer_utils/registry.py
  event_routing_backends/processors/xapi/tests/test_xapi.py
  event_routing_backends/processors/xapi/transformer_processor.py
  event_routing_backends/tasks.py
  event_routing_backends/utils/xapi_lrs_client.py
  requirements/base.txt
  requirements/dev.txt
  requirements/doc.txt
  requirements/pip.txt
  requirements/quality.txt
  requirements/test.txt
Labels: awaiting prioritization, open-source-contribution

#131 feat: Remove 'code' field from transformed xAPI video events' extensions.
  event_routing_backends/processors/xapi/event_transformers/video_events.py
  event_routing_backends/processors/xapi/tests/fixtures/expected/complete_video(proposed).json
  event_routing_backends/processors/xapi/tests/fixtures/expected/load_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/pause_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/play_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/seek_video.json
  event_routing_backends/processors/xapi/tests/fixtures/expected/stop_video.json
Labels: engineering review, open-source-contribution

#129 [ERTE-84] docs: updated application setup procedure
  docs/getting_started.rst
Labels: engineering review, open-source-contribution

#130 [ERTE-83] feat: added username, password authentication support in http client
  event_routing_backends/backends/tests/test_events_router.py
  event_routing_backends/utils/http_client.py
Labels: needs triage, open-source-contribution

#134 docs: updated list of events
  docs/event-mapping/list_of_supported_edx_events.rst
Labels: engineering review, open-source-contribution

#133 feat: Make event-routing-backend a plugin
  event_routing_backends/apps.py
  event_routing_backends/processors/xapi/__init__.py
  event_routing_backends/settings/__init__.py
  event_routing_backends/settings/common.py
  event_routing_backends/settings/devstack.py
  event_routing_backends/settings/production.py
  event_routing_backends/tests/test_settings.py
  setup.py
  test_settings.py
Labels: engineering review, open-source-contribution

#136 feat: added ablity to get anonymous user_id either by username or user_id
  event_routing_backends/helpers.py
  event_routing_backends/processors/caliper/transformer.py
  event_routing_backends/processors/mixins/base_transformer.py
  event_routing_backends/processors/xapi/event_transformers/enrollment_events.py
  event_routing_backends/processors/xapi/event_transformers/navigation_events.py
  event_routing_backends/processors/xapi/event_transformers/problem_interaction_events.py
  event_routing_backends/processors/xapi/event_transformers/video_events.py
  event_routing_backends/processors/xapi/transformer.py
  event_routing_backends/tasks.py
  event_routing_backends/tests/test_helpers.py
Labels: engineering review, open-source-contribution

#139 [ERTE-89] feat: Added support for multiple routers host configurations
  event_routing_backends/backends/events_router.py
  event_routing_backends/backends/tests/test_events_router.py
Labels: needs triage, open-source-contribution

#140 [ERTE-89] Refactor: Added Test case for multiple event routers
  event_routing_backends/backends/tests/test_events_router.py
Labels: needs triage, open-source-contribution
